### ISSUE TITLE
filename suggestion

### ISSUE THREAD

**Issue by epogrebnyak** [UBC-MDS/public#13]
```
2014-06-08_abstract-for-sla.docx
joes-filenames-are-getting-better.xlsx
fig01_scatterplot-talk-length-vs-interest.png
fig02_histogram-talk-attendance.png
1986-01-28_raw-data-from-challenger-o-rings.txt
```

In your filename suggestion, I think you can go a step further in organising naming and put a more general term `talk` forward. There is a similar practice  variables, eg putting `member_a` and `member_b`. 

The filenames in consideration could be:

```
fig01_talk-scatterplot-length-vs-interest.png
fig02_talk-histogram-attendance.png
```

**Comment by ttimbers** [comment]
Thanks @epogrebnyak - this is a great suggestion and I will incorporate this next fall when I teach the course again.

**Comment by joelostblom** [comment]
This was added to 521 so closing.
