### ISSUE TITLE
Need write access to upload pdf icons

### ISSUE THREAD

**Issue by nstbayless** [UBC-MDS/public#3]
@mgelbart 

Could you give me write access so I could upload the new pdf icons? Thanks.

Currently they're located here: https://github.com/UBC-MDS/rubrics/tree/master/rubric/icon
with the suffix _pdf.png

**Comment by mgelbart** [comment]
I don't think I have the ability to do that. Could you try a pull request?

**Comment by nstbayless** [comment]
Sure. https://github.com/UBC-MDS/public/pull/4

In the mean time they're hosted on my github.
